# Generated by Django 5.1 on 2024-08-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fechaNacimiento', models.CharField(max_length=200)),
                ('numeroPoliza', models.CharField(max_length=200)),
                ('numeroSeguro', models.CharField(max_length=200)),
                ('historiaMedica', models.CharField(max_length=200)),
                ('estadoOrden', models.CharField(default='Sin iniciar', max_length=200)),
            ],
        ),
    ]
