# Generated by Django 5.1 on 2024-08-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_empleados_pacientes'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='empleados.empleados'),
            preserve_default=False,
        ),
    ]
