# Generated by Django 5.1 on 2024-08-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='doctor',
            field=models.CharField(default='Sin iniciar', max_length=200),
        ),
    ]
