# Generated by Django 5.1 on 2024-08-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='doctor',
            field=models.CharField(max_length=200),
        ),
    ]
