# Generated by Django 5.1 on 2024-08-28 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_empleados_pacientes'),
        ('pacientes', '0004_alter_paciente_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='empleados.empleados'),
        ),
    ]
