# Generated by Django 5.1 on 2024-09-17 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_empleados_pacientes'),
        ('pacientes', '0005_alter_paciente_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='archivoAdjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos_pacientes/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='empleados.empleados'),
        ),
    ]
