# Generated by Django 5.1 on 2024-09-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_archivoadjunto_alter_paciente_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_fin_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_inicio_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
