# Generated by Django 5.1 on 2024-08-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleados_pacientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='pacientes',
        ),
    ]
